//! Wire and signed-field boundary acceptance tests.
//!
//! Expected changes are specified field-by-field rather than generated by an implementation
//! mutation helper. Literal vectors can be consumed by non-Rust transport and EVM tests.

use alloy_primitives::{Address, B256, U256};
use alloy_signer::SignerSync;
use alloy_signer_local::PrivateKeySigner;
use zone_fast_transfer::{EpochRoster, QuorumVerifier};
use zone_primitives::fast_transfer::{
    AssetId, CanonicalEncode, CertificateBody, MAX_CERTIFICATE_BYTES, OutcomeCertificate,
    PeerMessage, RejectionReason, SignatureBytes, TransferIntent, TransferOutcome, ZoneDomain,
    decode_exact,
};

fn address(byte: u8) -> Address {
    Address::from([byte; 20])
}

fn hash(byte: u8) -> B256 {
    B256::from([byte; 32])
}

fn domain(zone_id: u32, marker: u8) -> ZoneDomain {
    ZoneDomain {
        l1_chain_id: 0x0102_0304_0506_0708,
        zone_id,
        chain_id: 10_000 + u64::from(zone_id),
        portal: address(marker),
        authority_epoch: 7,
        roster_hash: hash(marker.wrapping_add(1)),
        protocol_version: 1,
    }
}

fn intent() -> TransferIntent {
    TransferIntent {
        source: domain(1, 0x11),
        destination: domain(2, 0x22),
        asset: AssetId {
            l1_token: address(0x31),
            source_token: address(0x32),
            destination_token: address(0x33),
            decimals: 6,
        },
        sender: address(0x41),
        recipient: address(0x42),
        refund_account: address(0x41),
        destination_pool: address(0x43),
        reimbursement_account: address(0x44),
        principal: U256::from(10_000_000_u64),
        fee: U256::from(123_u64),
        quote_id: hash(0x51),
        destination_expiry_height: 12_345,
        transfer_nonce: 99,
    }
}

fn body() -> CertificateBody {
    let intent = intent();
    body_for(&intent)
}

fn body_for(intent: &TransferIntent) -> CertificateBody {
    CertificateBody {
        transfer_id: intent.transfer_id(),
        intent_hash: intent.intent_hash(),
        zone: intent.destination,
        log_term: 3,
        log_index: 17,
        block_height: 29,
        block_hash: hash(0x61),
        state_root: hash(0x62),
        transaction_hash: hash(0x63),
        outcome: TransferOutcome::Paid {
            pool: intent.destination_pool,
            recipient: intent.recipient,
            principal: intent.principal,
        },
    }
}

fn verifier_fixture() -> (TransferIntent, QuorumVerifier, [PrivateKeySigner; 3]) {
    let signers = [
        PrivateKeySigner::from_bytes(&B256::from([0x91; 32])).unwrap(),
        PrivateKeySigner::from_bytes(&B256::from([0x92; 32])).unwrap(),
        PrivateKeySigner::from_bytes(&B256::from([0x93; 32])).unwrap(),
    ];
    let members = signers.each_ref().map(PrivateKeySigner::address);
    let mut intent = intent();
    intent.destination.roster_hash = EpochRoster::calculate_hash(intent.destination, members);
    let roster = EpochRoster::new(intent.destination, members).expect("valid three-member roster");
    (intent, QuorumVerifier::new(roster), signers)
}

fn sign_outcome(
    verifier: &QuorumVerifier,
    body: CertificateBody,
    signers: [&PrivateKeySigner; 2],
) -> OutcomeCertificate {
    let mut certificate = OutcomeCertificate {
        body,
        signatures: [SignatureBytes([0; 65]), SignatureBytes([0; 65])],
    };
    let digest = verifier.outcome_digest(&certificate);
    certificate.signatures = signers.map(|signer| {
        SignatureBytes(
            signer
                .sign_hash_sync(&digest)
                .expect("test signer signs digest")
                .as_bytes(),
        )
    });
    certificate
}

macro_rules! assert_intent_mutation_bound {
    ($base:ident, $mutation:expr) => {{
        let mut changed = $base.clone();
        $mutation(&mut changed);
        assert_ne!(
            changed.intent_hash(),
            $base.intent_hash(),
            "mutated intent field was not bound: {}",
            stringify!($mutation)
        );
    }};
}

macro_rules! assert_body_mutation_bound {
    ($base:ident, $mutation:expr) => {{
        let mut changed = $base.clone();
        $mutation(&mut changed);
        assert_ne!(
            changed.body_hash(),
            $base.body_hash(),
            "mutated certificate field was not signed: {}",
            stringify!($mutation)
        );
    }};
}

#[test]
fn every_intent_field_is_hash_bound_and_identity_fields_define_transfer_id() {
    let base = intent();
    base.validate().expect("acceptance vector is valid");

    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .source
        .l1_chain_id += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.source.zone_id += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.source.chain_id +=
        1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.source.portal =
        address(0x12));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .source
        .authority_epoch += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .source
        .roster_hash =
        hash(0x13));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .source
        .protocol_version +=
        1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .l1_chain_id += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .zone_id += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .chain_id += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .portal =
        address(0x23));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .authority_epoch += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .roster_hash =
        hash(0x24));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination
        .protocol_version +=
        1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.asset.l1_token =
        address(0x34));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .asset
        .source_token =
        address(0x35));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .asset
        .destination_token =
        address(0x36));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.asset.decimals += 1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.sender =
        address(0x45));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.recipient =
        address(0x46));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.refund_account =
        address(0x47));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.destination_pool =
        address(0x48));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .reimbursement_account =
        address(0x49));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.principal +=
        U256::ONE);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.fee += U256::ONE);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.quote_id =
        hash(0x52));
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value
        .destination_expiry_height +=
        1);
    assert_intent_mutation_bound!(base, |value: &mut TransferIntent| value.transfer_nonce += 1);

    let id = base.transfer_id();
    for changed in [
        TransferIntent {
            recipient: address(0x90),
            ..base.clone()
        },
        TransferIntent {
            principal: base.principal + U256::ONE,
            ..base.clone()
        },
        TransferIntent {
            fee: base.fee + U256::ONE,
            ..base.clone()
        },
        TransferIntent {
            quote_id: hash(0x91),
            ..base
        },
    ] {
        assert_eq!(
            changed.transfer_id(),
            id,
            "body-only changes must retain retry identity"
        );
        assert_ne!(changed.intent_hash(), base.intent_hash());
    }

    assert_ne!(
        TransferIntent {
            sender: address(0x92),
            ..base
        }
        .transfer_id(),
        id
    );
    assert_ne!(
        TransferIntent {
            transfer_nonce: 100,
            ..base
        }
        .transfer_id(),
        id
    );
    assert_ne!(
        TransferIntent {
            source: ZoneDomain {
                portal: address(0x93),
                ..base.source
            },
            ..base
        }
        .transfer_id(),
        id
    );
}

#[test]
fn every_certificate_body_and_outcome_field_is_signed() {
    let base = body();

    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.transfer_id =
        hash(0x70));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.intent_hash =
        hash(0x71));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value
        .zone
        .l1_chain_id += 1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.zone.zone_id += 1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.zone.chain_id += 1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.zone.portal =
        address(0x72));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value
        .zone
        .authority_epoch +=
        1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.zone.roster_hash =
        hash(0x73));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value
        .zone
        .protocol_version +=
        1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.log_term += 1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.log_index += 1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.block_height += 1);
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.block_hash =
        hash(0x74));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.state_root =
        hash(0x75));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.transaction_hash =
        hash(0x76));
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.outcome =
        TransferOutcome::Paid {
            pool: address(0x77),
            recipient: address(0x42),
            principal: U256::from(10_000_000_u64),
        });
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.outcome =
        TransferOutcome::Paid {
            pool: address(0x43),
            recipient: address(0x78),
            principal: U256::from(10_000_000_u64),
        });
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.outcome =
        TransferOutcome::Paid {
            pool: address(0x43),
            recipient: address(0x42),
            principal: U256::from(10_000_001_u64),
        });
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.outcome =
        TransferOutcome::Rejected {
            reason: RejectionReason::PolicyDenied,
        });
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.outcome =
        TransferOutcome::Released {
            beneficiary: address(0x44),
            amount: U256::from(10_000_123_u64),
        });
    assert_body_mutation_bound!(base, |value: &mut CertificateBody| value.outcome =
        TransferOutcome::Refunded {
            beneficiary: address(0x41),
            amount: U256::from(10_000_123_u64),
        });
}

#[test]
fn quorum_rejects_duplicate_unknown_epoch_and_mutated_signed_fields() {
    let (intent, verifier, signers) = verifier_fixture();
    let valid = sign_outcome(&verifier, body_for(&intent), [&signers[0], &signers[1]]);
    assert_eq!(verifier.verify_outcome(&valid, &intent).unwrap().len(), 2);

    let duplicate = sign_outcome(&verifier, body_for(&intent), [&signers[0], &signers[0]]);
    assert!(verifier.verify_outcome(&duplicate, &intent).is_err());

    macro_rules! assert_signed_mutation_rejected {
        ($mutation:expr) => {{
            let mut changed = valid.clone();
            $mutation(&mut changed.body);
            assert!(
                verifier.verify_outcome(&changed, &intent).is_err(),
                "signed mutation was accepted: {}",
                stringify!($mutation)
            );
        }};
    }

    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.transfer_id = hash(0xa0));
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.intent_hash = hash(0xa1));
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.zone.l1_chain_id += 1);
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.zone.zone_id += 1);
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.zone.chain_id += 1);
    assert_signed_mutation_rejected!(
        |value: &mut CertificateBody| value.zone.portal = address(0xa2)
    );
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.zone.authority_epoch += 1);
    assert_signed_mutation_rejected!(
        |value: &mut CertificateBody| value.zone.roster_hash = hash(0xa3)
    );
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.zone.protocol_version += 1);
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.log_term += 1);
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.log_index += 1);
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.block_height += 1);
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.block_hash = hash(0xa4));
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.state_root = hash(0xa5));
    assert_signed_mutation_rejected!(
        |value: &mut CertificateBody| value.transaction_hash = hash(0xa6)
    );
    assert_signed_mutation_rejected!(|value: &mut CertificateBody| value.outcome =
        TransferOutcome::Paid {
            pool: intent.destination_pool,
            recipient: address(0xa7),
            principal: intent.principal,
        });

    let mut old_epoch = valid;
    old_epoch.body.zone.authority_epoch = old_epoch.body.zone.authority_epoch.saturating_sub(1);
    assert!(verifier.verify_outcome(&old_epoch, &intent).is_err());
}

#[test]
fn bounded_decoders_reject_truncation_trailing_bytes_and_oversize_messages() {
    let encoded = intent().canonical_bytes();
    assert_eq!(
        TransferIntent::decode(&encoded).expect("valid intent"),
        intent()
    );

    for length in 0..encoded.len() {
        assert!(
            TransferIntent::decode(&encoded[..length]).is_err(),
            "truncated intent length {length} was accepted"
        );
    }
    let mut trailing = encoded;
    trailing.push(0);
    assert!(TransferIntent::decode(&trailing).is_err());

    let certificate = OutcomeCertificate {
        body: body(),
        signatures: [SignatureBytes([0x81; 65]), SignatureBytes([0x82; 65])],
    };
    let encoded = certificate.canonical_bytes();
    assert_eq!(
        OutcomeCertificate::decode(&encoded).expect("valid certificate"),
        certificate
    );
    let mut trailing = encoded;
    trailing.push(0);
    assert!(OutcomeCertificate::decode(&trailing).is_err());
    assert!(
        decode_exact::<PeerMessage>(&vec![0; MAX_CERTIFICATE_BYTES + 1], MAX_CERTIFICATE_BYTES)
            .is_err()
    );
}

#[test]
fn literal_transport_vectors_are_stable_across_languages() {
    let vector = ZoneDomain {
        l1_chain_id: 0x0102_0304_0506_0708,
        zone_id: 0x1112_1314,
        chain_id: 0x2122_2324_2526_2728,
        portal: address(0x31),
        authority_epoch: 0x4142_4344_4546_4748,
        roster_hash: hash(0x51),
        protocol_version: 0x6162,
    };
    let expected = [
        0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x11, 0x12, 0x13, 0x14, 0x21, 0x22, 0x23,
        0x24, 0x25, 0x26, 0x27, 0x28, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31,
        0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x31, 0x41, 0x42, 0x43, 0x44, 0x45,
        0x46, 0x47, 0x48, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51,
        0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51, 0x51,
        0x51, 0x51, 0x51, 0x51, 0x51, 0x61, 0x62,
    ];
    assert_eq!(vector.canonical_bytes(), expected);
    assert_eq!(
        decode_exact::<ZoneDomain>(&expected, expected.len()).unwrap(),
        vector
    );

    let acknowledgment = PeerMessage::Acknowledgment {
        stream: 0x0102_0304_0506_0708,
        sequence: 0x1112_1314_1516_1718,
    };
    let expected = [
        0x02, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16,
        0x17, 0x18,
    ];
    assert_eq!(acknowledgment.canonical_bytes(), expected);
    assert_eq!(
        decode_exact::<PeerMessage>(&expected, expected.len()).unwrap(),
        acknowledgment
    );
}
