[package]
name = "zone-primitives"
description = "Primitive types used by the zone"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
tempo-hardfork = { workspace = true }
thiserror = { version = "2", default-features = false }

[features]
default = ["std", "serde"]
std = ["alloy-primitives/std", "thiserror/std"]
serde = ["dep:alloy-rlp", "dep:serde", "alloy-primitives/serde"]
