[package]
name = "zone-prover"
description = "Prover protocol components for Tempo Zones"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempo-zone-contracts = { workspace = true, features = ["std"] }
zone-spf.workspace = true

tempo-chainspec.workspace = true

alloy-primitives.workspace = true
alloy-sol-types.workspace = true

futures.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["codec"] }

[dev-dependencies]
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
reth-trie-common.workspace = true
tempo-primitives.workspace = true
