use alloy_sol_types::SolEvent as _;
use tempo_zone_contracts::{IZoneInbox, IZoneOutbox, TempoState, ZoneFactory, ZonePortal};

use super::portal;

#[test]
fn independent_topics_match_shared_wire_types() {
    let topics = [
        (
            portal::DEPOSIT_MADE_TOPIC,
            ZonePortal::DepositMade::SIGNATURE_HASH,
        ),
        (
            portal::TOKEN_ENABLED_TOPIC,
            ZonePortal::TokenEnabled::SIGNATURE_HASH,
        ),
        (
            portal::BATCH_SUBMITTED_TOPIC,
            ZonePortal::BatchSubmitted::SIGNATURE_HASH,
        ),
        (
            portal::WITHDRAWAL_PROCESSED_TOPIC,
            ZonePortal::WithdrawalProcessed::SIGNATURE_HASH,
        ),
        (
            portal::WITHDRAWAL_BOUNCE_BACK_TOPIC,
            ZonePortal::WithdrawalBounceBack::SIGNATURE_HASH,
        ),
        (
            portal::DEPOSIT_BOUNCE_BACK_TOPIC,
            ZonePortal::DepositBounceBack::SIGNATURE_HASH,
        ),
        (
            portal::DEPOSIT_BOUNCE_BACK_PENDING_TOPIC,
            ZonePortal::DepositBounceBackPending::SIGNATURE_HASH,
        ),
        (
            portal::REFUND_CLAIMED_TOPIC,
            ZonePortal::RefundClaimed::SIGNATURE_HASH,
        ),
        (
            portal::BOUNCEBACK_GAS_UPDATED_TOPIC,
            ZonePortal::BouncebackGasUpdated::SIGNATURE_HASH,
        ),
        (
            portal::SEQUENCER_ENCRYPTION_KEY_UPDATED_TOPIC,
            ZonePortal::SequencerEncryptionKeyUpdated::SIGNATURE_HASH,
        ),
        (
            portal::ZONE_GAS_RATE_UPDATED_TOPIC,
            ZonePortal::ZoneGasRateUpdated::SIGNATURE_HASH,
        ),
        (
            portal::MAX_TEMPO_GAS_RATE_UPDATED_TOPIC,
            ZonePortal::MaxTempoGasRateUpdated::SIGNATURE_HASH,
        ),
        (
            portal::ADMIN_TRANSFER_STARTED_TOPIC,
            ZonePortal::AdminTransferStarted::SIGNATURE_HASH,
        ),
        (
            portal::ADMIN_TRANSFERRED_TOPIC,
            ZonePortal::AdminTransferred::SIGNATURE_HASH,
        ),
        (
            portal::ROLE_UPDATED_TOPIC,
            ZonePortal::RoleUpdated::SIGNATURE_HASH,
        ),
        (
            portal::ENFORCEMENT_MODES_UPDATED_TOPIC,
            ZonePortal::EnforcementModesUpdated::SIGNATURE_HASH,
        ),
        (
            portal::SEQUENCER_SET_UPDATED_TOPIC,
            ZonePortal::SequencerSetUpdated::SIGNATURE_HASH,
        ),
        (
            portal::LEADER_UPDATED_TOPIC,
            ZonePortal::LeaderUpdated::SIGNATURE_HASH,
        ),
        (
            portal::DEPOSITS_PAUSED_TOPIC,
            ZonePortal::DepositsPaused::SIGNATURE_HASH,
        ),
        (
            portal::DEPOSITS_RESUMED_TOPIC,
            ZonePortal::DepositsResumed::SIGNATURE_HASH,
        ),
        (
            portal::PORTAL_PAUSED_TOPIC,
            ZonePortal::PortalPaused::SIGNATURE_HASH,
        ),
        (
            portal::PORTAL_RESUMED_TOPIC,
            ZonePortal::PortalResumed::SIGNATURE_HASH,
        ),
        (
            portal::ABDICATION_SCHEDULED_TOPIC,
            ZonePortal::AbdicationScheduled::SIGNATURE_HASH,
        ),
        (
            portal::RPC_URL_UPDATED_TOPIC,
            ZonePortal::RpcUrlUpdated::SIGNATURE_HASH,
        ),
        (
            super::ZONE_CREATED_TOPIC,
            ZoneFactory::ZoneCreated::SIGNATURE_HASH,
        ),
        (
            super::OWNERSHIP_TRANSFERRED_TOPIC,
            ZoneFactory::OwnershipTransferred::SIGNATURE_HASH,
        ),
        (
            super::TEMPO_ADVANCED_TOPIC,
            IZoneInbox::TempoAdvanced::SIGNATURE_HASH,
        ),
        (
            super::DEPOSIT_PROCESSED_TOPIC,
            IZoneInbox::DepositProcessed::SIGNATURE_HASH,
        ),
        (
            super::DEPOSIT_FAILED_TOPIC,
            IZoneInbox::DepositFailed::SIGNATURE_HASH,
        ),
        (
            super::WITHDRAWAL_BOUNCE_BACK_PROCESSED_TOPIC,
            IZoneInbox::WithdrawalBounceBackProcessed::SIGNATURE_HASH,
        ),
        (
            super::WITHDRAWAL_BOUNCE_BACK_PENDING_TOPIC,
            IZoneInbox::WithdrawalBounceBackPending::SIGNATURE_HASH,
        ),
        (
            super::REFUND_CLAIMED_TOPIC,
            IZoneInbox::RefundClaimed::SIGNATURE_HASH,
        ),
        (
            super::INBOX_TOKEN_ENABLED_TOPIC,
            IZoneInbox::TokenEnabled::SIGNATURE_HASH,
        ),
        (
            super::DEPOSIT_REJECTED_TOPIC,
            IZoneInbox::DepositRejected::SIGNATURE_HASH,
        ),
        (
            super::WITHDRAWAL_REQUESTED_TOPIC,
            IZoneOutbox::WithdrawalRequested::SIGNATURE_HASH,
        ),
        (
            super::BATCH_FINALIZED_TOPIC,
            IZoneOutbox::BatchFinalized::SIGNATURE_HASH,
        ),
        (
            super::TEMPO_GAS_RATE_UPDATED_TOPIC,
            IZoneOutbox::TempoGasRateUpdated::SIGNATURE_HASH,
        ),
        (
            super::MAX_WITHDRAWALS_PER_BLOCK_UPDATED_TOPIC,
            IZoneOutbox::MaxWithdrawalsPerBlockUpdated::SIGNATURE_HASH,
        ),
        (
            super::BLOCK_FINALIZED_TOPIC,
            TempoState::TempoBlockFinalized::SIGNATURE_HASH,
        ),
    ];

    for (literal, generated) in topics {
        assert_eq!(literal, generated);
    }
}
