#!/usr/bin/env python3
"""Maintain the inventory of Prometheus metric names exported by Zone crates.

Alert rules outside this repository query these names directly, so a rename
silently turns an alert into a query with no data. CI runs `--check` to fail
when the source and `docs/metric-names.txt` disagree; update the inventory
with `--write` and adjust dependent alerts in the same change.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "docs" / "metric-names.txt"
SOURCE_DIRS = ("bin", "crates")
# Reth's Prometheus recorder prefixes every metric name.
PREFIX = "reth_"
KINDS = {"Counter": "counter", "Gauge": "gauge", "Histogram": "histogram"}

HEADER = """\
# Prometheus metric names exported by Zone crates, generated by
# `scripts/metric-names.py --write`. Histograms are exported as summaries with
# `_count`, `_sum` and `quantile` series.
#
# Alerts in tempoxyz/helm-charts (charts/tempo-zone-alerts) query these names.
# When this file changes, update every alert that uses a removed or renamed
# metric in the same release.
"""

MACRO = re.compile(r"(?<![\w])(counter|gauge|histogram)!\s*\(\s*")
METRICS_ATTR = re.compile(r"#\[metrics\(([^)]*)\)\]")
STRUCT = re.compile(r"\bstruct\s+(\w+)\s*\{")
FIELD = re.compile(
    r"((?:#\[[^\]]*\]\s*)*)(?:pub(?:\([^)]*\))?\s+)?(\w+)\s*:\s*([\w:]+)\s*,?"
)
RENAME = re.compile(r'#\[metric\([^\]]*rename\s*=\s*"([^"]+)"')


def strip_comments(src: str) -> str:
    """Blank out comments while keeping string literals and line numbers intact."""
    out = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if src.startswith("//", i):
            end = src.find("\n", i)
            end = n if end == -1 else end
            i = end
        elif src.startswith("/*", i):
            depth, j = 1, i + 2
            while j < n and depth:
                if src.startswith("/*", j):
                    depth, j = depth + 1, j + 2
                elif src.startswith("*/", j):
                    depth, j = depth - 1, j + 2
                else:
                    j += 1
            out.append("\n" * src.count("\n", i, j))
            i = j
        elif (m := re.match(r'r(#*)"', src[i:])) and (i == 0 or not (src[i - 1].isalnum() or src[i - 1] == "_")):
            close = '"' + m.group(1)
            end = src.find(close, i + len(m.group(0)))
            end = n if end == -1 else end + len(close)
            out.append(src[i:end])
            i = end
        elif c == '"':
            j = i + 1
            while j < n and src[j] != '"':
                j += 2 if src[j] == "\\" else 1
            out.append(src[i : j + 1])
            i = j + 1
        elif c == "'" and (m := re.match(r"'(?:\\.|\\u\{[0-9a-fA-F]+\}|[^\\'])'", src[i:])):
            out.append(src[i : i + len(m.group(0))])
            i += len(m.group(0))
        else:
            out.append(c)
            i += 1
    return "".join(out)


def matching_brace(src: str, open_idx: int) -> int:
    depth = 0
    for j in range(open_idx, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return j
    raise ValueError("unbalanced braces")


def line_of(src: str, idx: int) -> int:
    return src.count("\n", 0, idx) + 1


def collect(path: Path, metrics: dict[str, set[str]], errors: list[str]) -> None:
    src = strip_comments(path.read_text())
    rel = path.relative_to(ROOT)

    for attr in METRICS_ATTR.finditer(src):
        where = f"{rel}:{line_of(src, attr.start())}"
        args = attr.group(1)
        scope = re.search(r'scope\s*=\s*"([^"]+)"', args)
        separator = re.search(r'separator\s*=\s*"([^"]*)"', args)
        if "dynamic" in args or not scope:
            errors.append(f"{where}: only static `#[metrics(scope = ...)]` structs are supported")
            continue
        struct = STRUCT.search(src, attr.end())
        if not struct:
            errors.append(f"{where}: no struct follows the metrics attribute")
            continue
        open_idx = struct.end() - 1
        body = src[open_idx + 1 : matching_brace(src, open_idx)]
        sep = separator.group(1) if separator else "_"
        for field in FIELD.finditer(body):
            attrs, name, ty = field.groups()
            kind = KINDS.get(ty.rsplit("::", 1)[-1])
            if kind is None:
                errors.append(f"{where}: field `{name}` has unsupported metric type `{ty}`")
                continue
            if "#[metric(skip" in attrs.replace(" ", ""):
                continue
            rename = RENAME.search(attrs)
            metrics.setdefault(f"{PREFIX}{scope.group(1)}{sep}{rename.group(1) if rename else name}", set()).add(kind)

    for call in MACRO.finditer(src):
        literal = re.match(r'"([^"\\]+)"', src[call.end() :])
        if not literal:
            errors.append(
                f"{rel}:{line_of(src, call.start())}: `{call.group(1)}!` needs a string literal name "
                "so the metric inventory can track it"
            )
            continue
        metrics.setdefault(PREFIX + literal.group(1), set()).add(call.group(1))


def render() -> str:
    metrics: dict[str, set[str]] = {}
    errors: list[str] = []
    for directory in SOURCE_DIRS:
        for path in sorted((ROOT / directory).rglob("*.rs")):
            parts = path.relative_to(ROOT).parts
            if "target" in parts or "tests" in parts or "benches" in parts:
                continue
            collect(path, metrics, errors)
    if errors:
        sys.exit("error: " + "\nerror: ".join(errors))
    for name, kinds in metrics.items():
        if len(kinds) > 1:
            sys.exit(f"error: {name} is registered as more than one kind: {', '.join(sorted(kinds))}")
    lines = [f"{name} {next(iter(kinds))}" for name, kinds in sorted(metrics.items())]
    return HEADER + "\n" + "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if the inventory is stale")
    mode.add_argument("--write", action="store_true", help="regenerate the inventory")
    args = parser.parse_args()

    rendered = render()
    if args.write:
        INVENTORY.write_text(rendered)
        return

    current = INVENTORY.read_text() if INVENTORY.exists() else ""
    if current == rendered:
        return

    def names(text: str) -> set[str]:
        return {line.split()[0] for line in text.splitlines() if line and not line.startswith("#")}

    old, new = names(current), names(rendered)
    for name in sorted(old - new):
        print(f"removed: {name}")
    for name in sorted(new - old):
        print(f"added:   {name}")
    sys.exit(
        f"{INVENTORY.relative_to(ROOT)} is out of date. Run `scripts/metric-names.py --write`, "
        "commit the result, and update alerts in tempoxyz/helm-charts that use removed or renamed metrics."
    )


if __name__ == "__main__":
    main()
