//! Installs the native ZoneFactory marker, its shared runtimes, and EIP-2935 history into a
//! Tempo genesis file used by the local benchmark topology.

use alloy::{
    genesis::{Genesis, GenesisAccount},
    primitives::{Address, B256, Bytes, U256},
};
use alloy_eips::eip2935::{HISTORY_STORAGE_ADDRESS, HISTORY_STORAGE_CODE};
use eyre::{WrapErr as _, ensure};
use serde::Deserialize;
use std::{
    collections::BTreeMap,
    fs,
    io::Write as _,
    path::{Path, PathBuf},
};
use tempo_zone_contracts::{
    ZONE_FACTORY_ADDRESS, ZONE_MESSENGER_ADDRESS, ZONE_PORTAL_IMPL_ADDRESS, ZONE_VERIFIER_ADDRESS,
};

#[derive(Debug, clap::Parser)]
pub(crate) struct InstallReferenceZoneFactory {
    /// Tempo genesis JSON generated by tempo-xtask generate-localnet.
    #[arg(long)]
    genesis: PathBuf,

    /// Destination for the patched genesis. Refuses to overwrite an existing file.
    #[arg(short, long)]
    output: PathBuf,

    /// Address authorized to call ZoneFactory.createZone.
    #[arg(long)]
    owner: Address,

    /// Foundry output directory containing the shared Zone runtime artifacts.
    #[arg(long, default_value = "specs/ref-impls/out")]
    specs_out: PathBuf,
}

#[derive(Debug)]
struct NativeArtifacts {
    portal: Bytes,
    verifier: Bytes,
    messenger: Bytes,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FoundryArtifact {
    deployed_bytecode: DeployedBytecode,
}

#[derive(Debug, Deserialize)]
struct DeployedBytecode {
    object: String,
}

impl InstallReferenceZoneFactory {
    pub(crate) fn run(self) -> eyre::Result<()> {
        ensure!(
            self.owner != Address::ZERO,
            "--owner must not be the zero address"
        );
        ensure!(
            self.genesis != self.output,
            "--output must differ from --genesis; the source genesis is never modified"
        );
        ensure!(
            !self.output.exists(),
            "refusing to overwrite existing output `{}`",
            self.output.display()
        );

        let genesis_json = fs::read_to_string(&self.genesis)
            .wrap_err_with(|| format!("failed reading genesis `{}`", self.genesis.display()))?;
        let mut genesis: Genesis = serde_json::from_str(&genesis_json)
            .wrap_err_with(|| format!("failed parsing genesis `{}`", self.genesis.display()))?;

        let artifacts = load_native_artifacts(&self.specs_out)?;
        install_eip2935_history_storage(&mut genesis)?;
        install_native_zone_factory(&mut genesis, self.owner, artifacts)?;

        if let Some(parent) = self
            .output
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
        {
            fs::create_dir_all(parent).wrap_err_with(|| {
                format!("failed creating output directory `{}`", parent.display())
            })?;
        }
        let mut output = serde_json::to_string_pretty(&genesis)
            .wrap_err("failed serializing patched Tempo genesis")?;
        output.push('\n');
        let mut destination = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&self.output)
            .wrap_err_with(|| format!("failed creating `{}`", self.output.display()))?;
        destination
            .write_all(output.as_bytes())
            .wrap_err_with(|| format!("failed writing `{}`", self.output.display()))?;

        println!("Patched Tempo genesis written to {}", self.output.display());
        println!("  ZoneFactory: {ZONE_FACTORY_ADDRESS}");
        println!("  Portal impl: {ZONE_PORTAL_IMPL_ADDRESS}");
        println!("  Verifier:    {ZONE_VERIFIER_ADDRESS}");
        println!("  Messenger:   {ZONE_MESSENGER_ADDRESS}");
        println!("  EIP-2935:    {HISTORY_STORAGE_ADDRESS}");
        println!("  Owner:       {}", self.owner);
        Ok(())
    }
}

fn install_eip2935_history_storage(genesis: &mut Genesis) -> eyre::Result<()> {
    let expected = GenesisAccount::default()
        .with_nonce(Some(1))
        .with_code(Some(HISTORY_STORAGE_CODE.clone()));

    if let Some(existing) = genesis.alloc.get(&HISTORY_STORAGE_ADDRESS) {
        ensure!(
            existing == &expected,
            "refusing to replace conflicting EIP-2935 history allocation at {HISTORY_STORAGE_ADDRESS}"
        );
        return Ok(());
    }

    genesis.alloc.insert(HISTORY_STORAGE_ADDRESS, expected);
    Ok(())
}

fn load_native_artifacts(specs_out: &Path) -> eyre::Result<NativeArtifacts> {
    Ok(NativeArtifacts {
        portal: load_runtime(specs_out, "ZonePortal")?,
        verifier: load_runtime(specs_out, "Verifier")?,
        messenger: load_runtime(specs_out, "ZoneMessenger")?,
    })
}

fn load_runtime(specs_out: &Path, contract: &str) -> eyre::Result<Bytes> {
    let path = specs_out
        .join(format!("{contract}.sol"))
        .join(format!("{contract}.json"));
    let json = fs::read_to_string(&path).wrap_err_with(|| {
        format!(
            "failed reading {contract} artifact `{}`; run `forge build --root specs/ref-impls`",
            path.display()
        )
    })?;
    let artifact: FoundryArtifact = serde_json::from_str(&json)
        .wrap_err_with(|| format!("failed parsing {contract} artifact `{}`", path.display()))?;
    let object = artifact
        .deployed_bytecode
        .object
        .strip_prefix("0x")
        .unwrap_or(&artifact.deployed_bytecode.object);
    let bytecode = const_hex::decode(object)
        .wrap_err_with(|| format!("failed decoding {contract} deployed bytecode"))?;
    ensure!(
        !bytecode.is_empty(),
        "{contract} deployed bytecode is empty"
    );
    Ok(bytecode.into())
}

fn install_native_zone_factory(
    genesis: &mut Genesis,
    owner: Address,
    artifacts: NativeArtifacts,
) -> eyre::Result<()> {
    ensure!(owner != Address::ZERO, "ZoneFactory owner must not be zero");
    for (name, address) in [
        ("ZoneFactory", ZONE_FACTORY_ADDRESS),
        ("ZonePortal implementation", ZONE_PORTAL_IMPL_ADDRESS),
        ("Verifier", ZONE_VERIFIER_ADDRESS),
        ("ZoneMessenger", ZONE_MESSENGER_ADDRESS),
    ] {
        ensure!(
            !genesis.alloc.contains_key(&address),
            "refusing to replace existing genesis allocation for {name} at {address}"
        );
    }

    // Native TIP-1091 accounts use the non-empty 0xEF precompile marker. Slot zero packs
    // uint32 nextZoneId, address owner, and the implementation-lock flag.
    let packed_factory_config: U256 =
        U256::ONE | (U256::from_be_slice(owner.as_slice()) << 32_usize);
    let factory_storage =
        BTreeMap::from([(B256::ZERO, B256::from(packed_factory_config.to_be_bytes()))]);
    genesis.alloc.insert(
        ZONE_FACTORY_ADDRESS,
        GenesisAccount::default()
            .with_nonce(Some(1))
            .with_code(Some(Bytes::from_static(&[0xef])))
            .with_storage(Some(factory_storage)),
    );
    for (address, code) in [
        (ZONE_PORTAL_IMPL_ADDRESS, artifacts.portal),
        (ZONE_VERIFIER_ADDRESS, artifacts.verifier),
        (ZONE_MESSENGER_ADDRESS, artifacts.messenger),
    ] {
        genesis.alloc.insert(
            address,
            GenesisAccount::default()
                .with_nonce(Some(1))
                .with_code(Some(code)),
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::address;

    fn test_artifacts() -> NativeArtifacts {
        NativeArtifacts {
            portal: Bytes::from_static(&[0x60, 0x00]),
            verifier: Bytes::from_static(&[0x60, 0x01]),
            messenger: Bytes::from_static(&[0x60, 0x02]),
        }
    }

    #[test]
    fn installs_native_factory_and_shared_runtimes() {
        let owner = address!("0x0000000000000000000000000000000000001234");
        let mut genesis = Genesis::default();
        install_eip2935_history_storage(&mut genesis).unwrap();
        install_native_zone_factory(&mut genesis, owner, test_artifacts()).unwrap();

        let factory = &genesis.alloc[&ZONE_FACTORY_ADDRESS];
        assert_eq!(factory.nonce, Some(1));
        assert_eq!(
            factory.code.as_ref().map(|code| code.as_ref()),
            Some(&[0xef][..])
        );
        let packed: U256 = U256::ONE | (U256::from_be_slice(owner.as_slice()) << 32_usize);
        assert_eq!(
            factory.storage.as_ref().unwrap()[&B256::ZERO],
            B256::from(packed.to_be_bytes())
        );
        assert_eq!(genesis.alloc[&ZONE_PORTAL_IMPL_ADDRESS].nonce, Some(1));
        assert_eq!(genesis.alloc[&ZONE_VERIFIER_ADDRESS].nonce, Some(1));
        assert_eq!(genesis.alloc[&ZONE_MESSENGER_ADDRESS].nonce, Some(1));
        assert_eq!(
            genesis.alloc[&HISTORY_STORAGE_ADDRESS],
            GenesisAccount::default()
                .with_nonce(Some(1))
                .with_code(Some(HISTORY_STORAGE_CODE.clone()))
        );
    }

    #[test]
    fn accepts_existing_canonical_eip2935_history_storage() {
        let expected = GenesisAccount::default()
            .with_nonce(Some(1))
            .with_code(Some(HISTORY_STORAGE_CODE.clone()));
        let mut genesis = Genesis::default();
        genesis
            .alloc
            .insert(HISTORY_STORAGE_ADDRESS, expected.clone());
        install_eip2935_history_storage(&mut genesis).unwrap();
        assert_eq!(genesis.alloc[&HISTORY_STORAGE_ADDRESS], expected);
    }

    #[test]
    fn rejects_conflicting_eip2935_history_storage() {
        let mut genesis = Genesis::default();
        genesis.alloc.insert(
            HISTORY_STORAGE_ADDRESS,
            GenesisAccount::default().with_code(Some(Bytes::from_static(&[0x60, 0x00]))),
        );
        let error = install_eip2935_history_storage(&mut genesis).unwrap_err();
        assert!(error.to_string().contains("conflicting EIP-2935"));
    }

    #[test]
    fn rejects_existing_protocol_allocations() {
        let mut genesis = Genesis::default();
        genesis
            .alloc
            .insert(ZONE_FACTORY_ADDRESS, GenesisAccount::default());
        let error = install_native_zone_factory(
            &mut genesis,
            address!("0x0000000000000000000000000000000000001234"),
            test_artifacts(),
        )
        .unwrap_err();
        assert!(error.to_string().contains("refusing to replace"));
    }
}
