//! Installs the Solidity reference ZoneFactory at TIP-1091's canonical address in a Tempo
//! genesis file.
//!
//! The reference factory's constructor cannot run at its protocol-managed address on an ordinary
//! EVM chain. This command reproduces the constructor's code, nonce, and storage allocations so a
//! real Tempo localnet can create zones through the canonical address.

use alloy::{
    genesis::{Genesis, GenesisAccount},
    primitives::{Address, B256, Bytes, U256, address, keccak256},
    sol_types::SolValue,
};
use eyre::{WrapErr as _, ensure, eyre};
use serde::Deserialize;
use std::{
    collections::BTreeMap,
    fs,
    io::Write as _,
    path::{Path, PathBuf},
};
use tempo_zone_contracts::ZONE_FACTORY_ADDRESS;

const VERIFIER_ADDRESS: Address = address!("0x5aF2000000000000000000000000000000000001");
const MESSENGER_ADDRESS: Address = address!("0x5aF2000000000000000000000000000000000002");

#[derive(Debug, clap::Parser)]
pub(crate) struct InstallReferenceZoneFactory {
    /// Tempo genesis JSON generated by tempo-xtask generate-localnet.
    #[arg(long)]
    genesis: PathBuf,

    /// Destination for the patched genesis. Refuses to overwrite an existing file.
    #[arg(short, long)]
    output: PathBuf,

    /// Address authorized to call ZoneFactory.createZone.
    #[arg(long)]
    owner: Address,

    /// Foundry output directory containing the reference contract artifacts.
    #[arg(long, default_value = "specs/ref-impls/out")]
    specs_out: PathBuf,
}

#[derive(Debug)]
struct ReferenceArtifacts {
    factory: Bytes,
    verifier: Bytes,
    messenger: Bytes,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FoundryArtifact {
    deployed_bytecode: DeployedBytecode,
    #[serde(default)]
    storage_layout: StorageLayout,
}

#[derive(Debug, Deserialize)]
struct DeployedBytecode {
    object: String,
    #[serde(default, rename = "immutableReferences")]
    immutable_references: BTreeMap<String, Vec<ImmutableReference>>,
}

#[derive(Debug, Deserialize)]
struct ImmutableReference {
    start: usize,
    length: usize,
}

#[derive(Debug, Default, Deserialize)]
struct StorageLayout {
    #[serde(default)]
    storage: Vec<StorageEntry>,
}

#[derive(Debug, Deserialize)]
struct StorageEntry {
    label: String,
    offset: usize,
    slot: String,
    #[serde(rename = "type")]
    type_name: String,
}

impl InstallReferenceZoneFactory {
    pub(crate) fn run(self) -> eyre::Result<()> {
        ensure!(
            self.owner != Address::ZERO,
            "--owner must not be the zero address"
        );
        ensure!(
            self.genesis != self.output,
            "--output must differ from --genesis; the source genesis is never modified"
        );
        ensure!(
            !self.output.exists(),
            "refusing to overwrite existing output `{}`",
            self.output.display()
        );

        let genesis_json = fs::read_to_string(&self.genesis)
            .wrap_err_with(|| format!("failed reading genesis `{}`", self.genesis.display()))?;
        let mut genesis: Genesis = serde_json::from_str(&genesis_json)
            .wrap_err_with(|| format!("failed parsing genesis `{}`", self.genesis.display()))?;

        let artifacts = load_reference_artifacts(&self.specs_out)?;
        install_reference_zone_factory(&mut genesis, self.owner, artifacts)?;

        if let Some(parent) = self
            .output
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
        {
            fs::create_dir_all(parent).wrap_err_with(|| {
                format!("failed creating output directory `{}`", parent.display())
            })?;
        }
        let mut output = serde_json::to_string_pretty(&genesis)
            .wrap_err("failed serializing patched Tempo genesis")?;
        output.push('\n');
        let mut destination = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&self.output)
            .wrap_err_with(|| format!("failed creating `{}`", self.output.display()))?;
        destination
            .write_all(output.as_bytes())
            .wrap_err_with(|| format!("failed writing `{}`", self.output.display()))?;

        println!("Patched Tempo genesis written to {}", self.output.display());
        println!("  ZoneFactory: {ZONE_FACTORY_ADDRESS}");
        println!("  Verifier:    {VERIFIER_ADDRESS}");
        println!("  Messenger:   {MESSENGER_ADDRESS}");
        println!("  Owner:       {}", self.owner);
        Ok(())
    }
}

fn load_reference_artifacts(specs_out: &Path) -> eyre::Result<ReferenceArtifacts> {
    let factory_artifact = load_artifact(specs_out, "ZoneFactory")?;
    validate_factory_storage_layout(&factory_artifact.storage_layout)?;
    let verifier_artifact = load_artifact(specs_out, "Verifier")?;
    let messenger_artifact = load_artifact(specs_out, "ZoneMessenger")?;

    let factory = decode_runtime("ZoneFactory", &factory_artifact.deployed_bytecode.object)?;
    let verifier = decode_runtime("Verifier", &verifier_artifact.deployed_bytecode.object)?;
    let mut messenger = decode_runtime(
        "ZoneMessenger",
        &messenger_artifact.deployed_bytecode.object,
    )?
    .to_vec();
    patch_messenger_factory_immutable(
        &mut messenger,
        &messenger_artifact.deployed_bytecode.immutable_references,
    )?;

    Ok(ReferenceArtifacts {
        factory,
        verifier,
        messenger: messenger.into(),
    })
}

fn load_artifact(specs_out: &Path, contract: &str) -> eyre::Result<FoundryArtifact> {
    let path = specs_out
        .join(format!("{contract}.sol"))
        .join(format!("{contract}.json"));
    let json = fs::read_to_string(&path).wrap_err_with(|| {
        format!(
            "failed reading {contract} artifact `{}`; run `forge build --root specs/ref-impls`",
            path.display()
        )
    })?;
    serde_json::from_str(&json)
        .wrap_err_with(|| format!("failed parsing {contract} artifact `{}`", path.display()))
}

fn decode_runtime(contract: &str, object: &str) -> eyre::Result<Bytes> {
    let object = object.strip_prefix("0x").unwrap_or(object);
    let bytecode = const_hex::decode(object)
        .wrap_err_with(|| format!("failed decoding {contract} deployed bytecode"))?;
    ensure!(
        !bytecode.is_empty(),
        "{contract} deployed bytecode is empty"
    );
    Ok(bytecode.into())
}

fn validate_factory_storage_layout(layout: &StorageLayout) -> eyre::Result<()> {
    let expected = [
        ("_nextZoneId", "0", 0, "t_uint32"),
        ("_validVerifiers", "3", 0, "t_mapping(t_address,t_bool)"),
        ("_verifier", "4", 0, "t_address"),
        ("_messenger", "5", 0, "t_address"),
        ("owner", "6", 0, "t_address"),
        ("_deploymentNonce", "7", 0, "t_uint256"),
    ];

    for (label, slot, offset, type_name) in expected {
        let entry = layout
            .storage
            .iter()
            .find(|entry| entry.label == label)
            .ok_or_else(|| eyre!("ZoneFactory artifact is missing storage entry `{label}`"))?;
        ensure!(
            entry.slot == slot && entry.offset == offset && entry.type_name == type_name,
            "ZoneFactory storage entry `{label}` changed: expected slot {slot}, offset {offset}, type {type_name}; got slot {}, offset {}, type {}",
            entry.slot,
            entry.offset,
            entry.type_name
        );
    }
    Ok(())
}

fn patch_messenger_factory_immutable(
    bytecode: &mut [u8],
    references: &BTreeMap<String, Vec<ImmutableReference>>,
) -> eyre::Result<()> {
    let references: Vec<_> = references.values().flatten().collect();
    ensure!(
        !references.is_empty(),
        "ZoneMessenger artifact has no immutable references"
    );

    for reference in references {
        ensure!(
            reference.length == 32,
            "ZoneMessenger immutable has unexpected length {}",
            reference.length
        );
        let end = reference
            .start
            .checked_add(reference.length)
            .ok_or_else(|| eyre!("ZoneMessenger immutable range overflowed"))?;
        ensure!(
            end <= bytecode.len(),
            "ZoneMessenger immutable range {}..{} exceeds runtime length {}",
            reference.start,
            end,
            bytecode.len()
        );
        bytecode[reference.start..end].fill(0);
        bytecode[reference.start + 12..end].copy_from_slice(ZONE_FACTORY_ADDRESS.as_slice());
    }
    Ok(())
}

fn install_reference_zone_factory(
    genesis: &mut Genesis,
    owner: Address,
    artifacts: ReferenceArtifacts,
) -> eyre::Result<()> {
    ensure!(owner != Address::ZERO, "ZoneFactory owner must not be zero");
    for (name, address) in [
        ("ZoneFactory", ZONE_FACTORY_ADDRESS),
        ("Verifier", VERIFIER_ADDRESS),
        ("ZoneMessenger", MESSENGER_ADDRESS),
    ] {
        ensure!(
            !genesis.alloc.contains_key(&address),
            "refusing to replace existing genesis allocation for {name} at {address}"
        );
    }

    let one = B256::with_last_byte(1);
    let mut factory_storage = BTreeMap::new();
    factory_storage.insert(B256::ZERO, one);
    factory_storage.insert(
        keccak256((VERIFIER_ADDRESS, U256::from(3)).abi_encode()),
        one,
    );
    factory_storage.insert(
        B256::with_last_byte(4),
        B256::left_padding_from(VERIFIER_ADDRESS.as_slice()),
    );
    factory_storage.insert(
        B256::with_last_byte(5),
        B256::left_padding_from(MESSENGER_ADDRESS.as_slice()),
    );
    factory_storage.insert(
        B256::with_last_byte(6),
        B256::left_padding_from(owner.as_slice()),
    );
    factory_storage.insert(B256::with_last_byte(7), B256::with_last_byte(3));

    genesis.alloc.insert(
        ZONE_FACTORY_ADDRESS,
        GenesisAccount::default()
            .with_nonce(Some(3))
            .with_code(Some(artifacts.factory))
            .with_storage(Some(factory_storage)),
    );
    genesis.alloc.insert(
        VERIFIER_ADDRESS,
        GenesisAccount::default()
            .with_nonce(Some(1))
            .with_code(Some(artifacts.verifier)),
    );
    genesis.alloc.insert(
        MESSENGER_ADDRESS,
        GenesisAccount::default()
            .with_nonce(Some(1))
            .with_code(Some(artifacts.messenger)),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_artifacts() -> ReferenceArtifacts {
        let mut messenger = vec![0x60; 64];
        messenger[4..36].fill(0);
        messenger[16..36].copy_from_slice(ZONE_FACTORY_ADDRESS.as_slice());
        ReferenceArtifacts {
            factory: Bytes::from_static(&[0x60, 0x00]),
            verifier: Bytes::from_static(&[0x60, 0x01]),
            messenger: messenger.into(),
        }
    }

    #[test]
    fn installs_constructor_equivalent_factory_state() {
        let owner = address!("0x0000000000000000000000000000000000001234");
        let mut genesis = Genesis::default();
        install_reference_zone_factory(&mut genesis, owner, test_artifacts()).unwrap();

        let factory = &genesis.alloc[&ZONE_FACTORY_ADDRESS];
        assert_eq!(factory.nonce, Some(3));
        assert_eq!(
            factory.code.as_ref().map(|code| code.as_ref()),
            Some(&[0x60, 0x00][..])
        );
        let storage = factory.storage.as_ref().unwrap();
        assert_eq!(storage[&B256::ZERO], B256::with_last_byte(1));
        assert_eq!(
            storage[&keccak256((VERIFIER_ADDRESS, U256::from(3)).abi_encode())],
            B256::with_last_byte(1)
        );
        assert_eq!(
            storage[&B256::with_last_byte(4)],
            B256::left_padding_from(VERIFIER_ADDRESS.as_slice())
        );
        assert_eq!(
            storage[&B256::with_last_byte(5)],
            B256::left_padding_from(MESSENGER_ADDRESS.as_slice())
        );
        assert_eq!(
            storage[&B256::with_last_byte(6)],
            B256::left_padding_from(owner.as_slice())
        );
        assert_eq!(storage[&B256::with_last_byte(7)], B256::with_last_byte(3));
        assert_eq!(genesis.alloc[&VERIFIER_ADDRESS].nonce, Some(1));
        assert_eq!(genesis.alloc[&MESSENGER_ADDRESS].nonce, Some(1));
    }

    #[test]
    fn rejects_existing_protocol_allocations() {
        let mut genesis = Genesis::default();
        genesis
            .alloc
            .insert(ZONE_FACTORY_ADDRESS, GenesisAccount::default());
        let error = install_reference_zone_factory(
            &mut genesis,
            address!("0x0000000000000000000000000000000000001234"),
            test_artifacts(),
        )
        .unwrap_err();
        assert!(error.to_string().contains("refusing to replace"));
    }

    #[test]
    fn patches_all_messenger_immutable_references() {
        let mut bytecode = vec![0xff; 96];
        let references = BTreeMap::from([(
            "42".to_owned(),
            vec![
                ImmutableReference {
                    start: 4,
                    length: 32,
                },
                ImmutableReference {
                    start: 48,
                    length: 32,
                },
            ],
        )]);
        patch_messenger_factory_immutable(&mut bytecode, &references).unwrap();
        for start in [4, 48] {
            assert_eq!(&bytecode[start..start + 12], &[0; 12]);
            assert_eq!(
                &bytecode[start + 12..start + 32],
                ZONE_FACTORY_ADDRESS.as_slice()
            );
        }
    }

    #[test]
    fn validates_factory_storage_slots() {
        let storage = [
            ("_nextZoneId", "0", "t_uint32"),
            ("_validVerifiers", "3", "t_mapping(t_address,t_bool)"),
            ("_verifier", "4", "t_address"),
            ("_messenger", "5", "t_address"),
            ("owner", "6", "t_address"),
            ("_deploymentNonce", "7", "t_uint256"),
        ]
        .into_iter()
        .map(|(label, slot, type_name)| StorageEntry {
            label: label.to_owned(),
            offset: 0,
            slot: slot.to_owned(),
            type_name: type_name.to_owned(),
        })
        .collect();
        validate_factory_storage_layout(&StorageLayout { storage }).unwrap();
    }
}
