name: Build binaries

on:
  workflow_dispatch:
    inputs:
      profile:
        default: "maxperf"
        description: "Build profile"
        type: choice
        options:
          - "release"
          - "maxperf"
          - "profiling"

permissions: {}

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/rust-build-binaries.yml@89eccc47fadc422ccf04b957a24125bba1596f2d # main
    with:
      binaries: tempo-zone
      profile: ${{ inputs.profile || 'maxperf' }}
      rust-toolchain: "1.96.0"
      runs-on: depot-ubuntu-latest-16
      retention-days: 90
