name: Build binaries

on:
  workflow_dispatch:
    inputs:
      profile:
        default: "maxperf"
        description: "Build profile"
        type: choice
        options:
          - "release"
          - "maxperf"
          - "profiling"

permissions:
  contents: read

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/rust-build-binaries.yml@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63
    with:
      binaries: tempo-zone
      profile: ${{ inputs.profile || 'maxperf' }}
      runs-on: depot-ubuntu-latest-16
      retention-days: 90
