name: Dependency Scan

on:
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63
