name: Dependency Scan

on:
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@68851d67c611dc0050e9f3fcd5bd47f3f899a00e
