name: Docker Build (Profiling)

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/tempoxyz

jobs:
  build-and-push:
    name: Build and Push Profiling Docker Images
    runs-on: depot-ubuntu-latest-16
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: tempoxyz/gh-actions/vendor/depot/setup-action@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63

      - name: Docker metadata for tempo-zone-profiling
        id: meta-tempo-zone
        uses: tempoxyz/gh-actions/vendor/docker/metadata-action@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63
        with:
          images: ${{ env.REGISTRY }}/tempo-zone
          bake-target: tempo-zone
          tags: |
            type=raw,value=profiling
            type=sha,prefix=profiling-sha-

      - name: Log in to Container Registry
        uses: tempoxyz/gh-actions/vendor/docker/login-action@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: shortsha
        run: echo "shortsha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: tempoxyz/gh-actions/vendor/depot/bake-action@55fe3b63d9612623cc51e6c62d9d62fbcb175fb0 # 2026-09-29T01-25-15Z-55fe3b63
        with:
          files: |
            docker/docker-bake.hcl
            docker/docker-bake-profiling.hcl
            ${{ steps.meta-tempo-zone.outputs.bake-file }}
          targets: tempo-zone
          project: 0c6tg19qsp
          push: true
          no-cache: true
          pull: true
        env:
          VERGEN_GIT_SHA: ${{ github.sha }}
          VERGEN_GIT_SHA_SHORT: ${{ steps.shortsha.outputs.shortsha }}
