name: Label PRs

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  label:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: tempoxyz/gh-actions/.github/workflows/label-prs.yml@bd66336ead0e97e3939428f526dc61fb43db0996 # 2026-09-25T20-13-44Z-bd66336e
