name: Label PRs

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  label:
    permissions:
      contents: read
      issues: write
    uses: tempoxyz/gh-actions/.github/workflows/label-prs.yml@98b1081dcf34361b576aca2ab3041772708582ef
