name: Label PRs

on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  label:
    permissions:
      contents: read
      issues: write
    uses: tempoxyz/gh-actions/.github/workflows/label-prs.yml@512158c4e90e42eef8aa7fc3fc3186a79b5b4648
