name: Lint

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  rust:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/rust-lint.yml@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819
    with:
      rust-toolchain: nightly-2026-02-21

  lint-success:
    name: lint success
    runs-on: ubuntu-latest
    if: always()
    permissions:
      id-token: write
    needs:
      - rust
    timeout-minutes: 30
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819

      - name: Decide whether the needed jobs succeeded or failed
        uses: tempoxyz/gh-actions/actions/check-needs@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819
        with:
          jobs: ${{ toJSON(needs) }}
