name: Lint

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  rust:
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/rust-lint.yml@0a60d757d0f4725a34f22f7b9ebf7b91b4b00bcf
    with:
      rust-toolchain: nightly-2026-02-21

  lint-success:
    name: lint success
    runs-on: ubuntu-latest
    if: always()
    permissions:
      id-token: write
    needs:
      - rust
    timeout-minutes: 30
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@0a60d757d0f4725a34f22f7b9ebf7b91b4b00bcf

      - name: Decide whether the needed jobs succeeded or failed
        uses: tempoxyz/gh-actions/actions/check-needs@0a60d757d0f4725a34f22f7b9ebf7b91b4b00bcf
        with:
          jobs: ${{ toJSON(needs) }}
