name: Scan GitHub Actions

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
  workflow_dispatch:
  schedule:
    - cron: "19 7 * * 1"

permissions: {}

jobs:
  scan:
    name: Scan GitHub Actions
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@5829d6b46418710f752eb8b25218af9812b78428
    permissions:
      actions: read
      contents: read
