name: Scan GitHub Actions

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
  workflow_dispatch:
  schedule:
    - cron: "19 7 * * 1"

permissions: {}

jobs:
  scan:
    name: Scan GitHub Actions
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@512158c4e90e42eef8aa7fc3fc3186a79b5b4648
    permissions:
      actions: read
      contents: read
