name: Test

permissions: {}

on:
  push:
    branches: [main]
    paths-ignore:
      - "specs/ref-impls/**"
      - ".github/workflows/specs.yml"
  pull_request:
    paths-ignore:
      - "specs/ref-impls/**"
      - ".github/workflows/specs.yml"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: "sccache"

jobs:
  test:
    name: test
    runs-on: depot-ubuntu-latest-16
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      - uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: nextest@0.9.124
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1.7.0
        with:
          version: nightly
      - name: Build Solidity artifacts
        working-directory: specs/ref-impls
        run: forge build
      - name: Build and compile tests
        run: cargo nextest run --profile ci --no-run
      - name: Run tests
        run: cargo nextest run --profile ci

  test-success:
    name: test success
    runs-on: ubuntu-latest
    if: always()
    permissions: {}
    needs:
      - test
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
