name: Test

permissions: {}

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/specs/**"
      - ".github/workflows/docs-specs.yml"
  pull_request:
    paths-ignore:
      - "docs/specs/**"
      - ".github/workflows/docs-specs.yml"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: "sccache"

jobs:
  test:
    name: test
    runs-on: depot-ubuntu-latest-16
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      - uses: taiki-e/install-action@3f67faa728964808f52294a9cd15561b15550b28 # v2.67.19
        with:
          tool: nextest@0.9.124
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Build Solidity artifacts
        working-directory: docs/specs
        run: forge build
      - name: Build and compile tests
        run: cargo nextest run --profile ci --no-run
      - name: Run tests
        run: cargo nextest run --profile ci

  test-success:
    name: test success
    runs-on: ubuntu-latest
    if: always()
    permissions: {}
    needs:
      - test
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
